// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.projectvolumemanagement.domain;

import com.projectvolumemanagement.domain.CheckProduck;

privileged aspect CheckProduck_Roo_JavaBean {
    
    public String CheckProduck.getName() {
        return this.Name;
    }
    
    public void CheckProduck.setName(String Name) {
        this.Name = Name;
    }
    
}
